volumes:
  server_node_modules:
  client_node_modules:
  worker_node_modules:
  db_data:
  ollama:
  cache:
services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build:
      context: ./server
    container_name: server
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
      - ./server/prisma:/app/prisma
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env
    depends_on:
      - db
      - cache

  client:
    build:
      context: ./client
    container_name: client
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    ports:
      - "5173:5173"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  worker: 
    build: 
      context: ./worker
    container_name: worker
    volumes:
      - ./worker:/app
      - worker_node_modules:/app/node_modules
      - ./server/prisma:/app/prisma
    env_file: 
      - ./worker/.env
    depends_on: 
      - db
      - cache

  cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
